// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class InteractionsTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void interactions() {
    driver.get("https://demoqa.com/");
    driver.manage().window().setSize(new Dimension(1382, 744));
    driver.findElement(By.cssSelector(".card:nth-child(5) .avatar")).click();
    driver.findElement(By.cssSelector(".show #item-0 > .text")).click();
    driver.findElement(By.id("sortableContainer")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".vertical-list-container > .list-group-item:nth-child(1)"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".vertical-list-container"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.cssSelector(".vertical-list-container")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".vertical-list-container > .list-group-item:nth-child(2)"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".vertical-list-container"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.cssSelector(".vertical-list-container")).click();
    driver.findElement(By.id("demo-tab-grid")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".create-grid > .list-group-item:nth-child(2)"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".create-grid"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.cssSelector(".create-grid")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".create-grid > .list-group-item:nth-child(5)"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".create-grid"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.cssSelector(".create-grid")).click();
    driver.findElement(By.cssSelector(".show #item-1")).click();
    driver.findElement(By.cssSelector(".mt-2:nth-child(1)")).click();
    driver.findElement(By.cssSelector(".mt-2:nth-child(2)")).click();
    driver.findElement(By.cssSelector(".mt-2:nth-child(3)")).click();
    driver.findElement(By.id("demo-tab-grid")).click();
    driver.findElement(By.cssSelector("#row2 > .list-group-item:nth-child(2)")).click();
    driver.findElement(By.cssSelector("#row1 > .list-group-item:nth-child(2)")).click();
    driver.findElement(By.cssSelector("#row1 > .list-group-item:nth-child(1)")).click();
    driver.findElement(By.cssSelector("#row2 > .list-group-item:nth-child(1)")).click();
    driver.findElement(By.cssSelector("#row1 > .list-group-item:nth-child(3)")).click();
    driver.findElement(By.cssSelector(".show #item-2")).click();
    driver.findElement(By.id("resizable")).click();
    driver.findElement(By.cssSelector(".show #item-3 > .text")).click();
    {
      WebElement element = driver.findElement(By.id("draggable"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".col-md-6"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".col-md-6"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.id("draggable")).click();
    driver.findElement(By.cssSelector(".col-md-6")).click();
    driver.findElement(By.cssSelector(".show #item-4")).click();
    {
      WebElement element = driver.findElement(By.id("dragBox"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.id("dragBox"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.id("dragBox"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.id("dragBox")).click();
    driver.findElement(By.id("draggableExample-tab-axisRestriction")).click();
    driver.findElement(By.id("draggableExample-tab-containerRestriction")).click();
    driver.findElement(By.id("draggableExample-tab-cursorStyle")).click();
  }
}
